backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "poemes"
    label: "Poèmes"
    folder: "poemes"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titre"
        name: "title"
        widget: "string"
      - label: "Illustration"
        name: "image"
        widget: "image"
        required: false
      - label: "Contenu"
        name: "body"
        widget: "markdown"
